server:
  port: 8088
  servlet:
    context-path: /luckymoney

#minMoney: 1
#maxMoney: 999
#deacription: 最少要发${minMoney}元
limit:
  minMoney: 1
  maxMoney: 999
  description: 最少要发${limit.minMoney}元,最多要发${limit.maxMoney}元
